name: Pre-Prod Deploy

on:
  push:
    branches:
      - pre-prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build Client
        working-directory: ./client
        run: |
          npm ci
          npm run build
          ls -l dist

      - name: Install Server Dependencies
        working-directory: ./server
        run: |
          npm ci
          ls -l

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.PREPROD_HOST }}
          username: ubuntu
          key: ${{ secrets.PREPROD_SSH_KEY }}
          port: 22
          source: |
            client/dist
            server
          target: /home/ubuntu/urbannook-pre-prod
          debug: true

      - name: Restart Server on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.PREPROD_HOST }}
          username: ubuntu
          key: ${{ secrets.PREPROD_SSH_KEY }}
          script: |
            cd /home/ubuntu/urbannook-pre-prod/server
            pm2 restart urbannook-preprod || pm2 start src/server.js --name urbannook-preprod
